import math
import numpy
import matplotlib.pyplot as plt
v0=float(input("Podaj prędkość początkową obiektu: "))
a=int(input("Podaj kąt pod którym zostanie rzucony obiekt: "))
vy=abs(v0*numpy.sin(a))
vx=abs(v0*numpy.cos(a))
g=9.81
czaslotu=abs(float((2*v0*math.sin(a))/g))
czas=numpy.arange(0,czaslotu,0.01)
poy = abs((vy*czas)-((g*(czas*czas))/2))
pox = abs(vx*czas)
czaswznoszenia=abs(vy/g)
hmax=abs((vy*czaswznoszenia)-((g*(czaswznoszenia*czaswznoszenia))/2))
zasieg=abs(vx*czaslotu)
vypr=abs((vy-g*czas)*(vy-g*czas))
vwt=numpy.sqrt(vypr+(vx*vx))
print("Odpowiedzi:","\n","Ciało wzniesie się do ","%.2f" % hmax," metrów nad ziemię","\n","Zasięg rzutu wynosi: ","%.2f" % zasieg," metrów","\n","Czas lotu wynosi: ","%.2f" % czaslotu," sekund","\n")
"""
plt.plot(czas,vwt)
plt.xlabel('t[s]')
plt.ylabel('v[m/s]')
plt.title("Wykres prędkości od czasu")
plt.show()
plt.plot(pox,poy)
plt.xlabel('s[m]')
plt.ylabel('h[m]')
plt.title("Trajektoria lotu obiektu")
plt.show()
plt.plot(czas,poy)
plt.xlabel('s[m]')
plt.ylabel('h[m]')
plt.title("Wykres wysokości od czasu")
plt.show()
"""




fig,(ax1,ax2,ax3) = plt.subplots(3)
ax1.plot(czas,vwt)
ax1.set_title('Wykres prędkości od czasu')
ax1.set_ylabel('V[s/t]')
ax1.set_xlabel('t[s]')
ax2.plot(pox,poy)
ax2.set_title('Trajektoria lotu obiektu')
ax2.set_ylabel('h[m]')
ax2.set_xlabel('s[m]')
ax3.plot(czas,poy)
ax3.set_title('Wykres wysokości od czasu')
ax3.set_ylabel('h[m]')
ax3.set_xlabel('t[s]')
fig.subplots_adjust(hspace=0.60,left=0.30,right=0.70,top=0.95,bottom=0.05)
plt.show()
plt.close()
